project:
  name: 'PCL'
  lacrNo: 'lno01'
  systemApplication: 'sapp01'
  systemId: 'sId01'
  contextName: 'extfunc05'
  warName: 'extfunc05.war'
  dName: 'PCL'
  owner: 'mark, johnson, roger'
  supervisor: 'andy, johnson'
  vendorQm: 'mark, huang, handsome'

form:
  uat:
    actions:
      action1:
        - 'Hello uat.'

ap145:
  dName: 'PCL\PHASE4'
  projectFolderName: 'extfunc05_PCL4'

pat:
  deployNote: '我是你大爺'