form:
  image:
    signature:
      path: 'C:\Users\markh\IdeaProjects\WordGenerator\src\main\resources\image'
  actions:
    action1:
      - 'Follow Jenkins handbook to execute checkin, build and move job.'
    action2:
      - 'Move all files from \\apacctltwuat145\COLA\Jenkins_upload\Build_{{lcfg.project.name}}'
      - 'to \\apacctltwuat145\COLA\COLA_AP_Deploy\{{lcfg.ap145.projectFolderName}}'
    action3:
      - 'Stop AP.'
    action4:
      - 'Un-zip D zip file and COPY ALL files from un-zip folder D\{{lcfg.project.dName}} to \\apacctltwuat145\{{lcfg.ap145.dName}}'
    action5:
      - 'Follow websphere guide to change AP.'

citi:
  project:
    relativePathPrefix: '@iisi/repos'
